#ifndef PRDCOIN_CHAINPARAMSSEEDS_H
#define PRDCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the predatorcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
       {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x7f,0x00,0x00,0x01}, 8710},
};

static SeedSpec6 pnSeed6_test[] = {};
#endif // PRDCOIN_CHAINPARAMSSEEDS_H
